# Generated by Django 6.0.6 on 2026-06-23 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=120, verbose_name='客户名称')),
                ('contact_name', models.CharField(blank=True, max_length=60, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=240, verbose_name='地址')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('resource_type', models.CharField(choices=[('suzhou', '苏州实验室'), ('jiangyin', '江阴实验室'), ('outsource', '委外供应商')], max_length=20, verbose_name='执行主体')),
                ('owner_name', models.CharField(max_length=100, verbose_name='项目负责人/供应商')),
                ('task_name', models.CharField(max_length=160, verbose_name='试验任务')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='成本/报价')),
                ('note', models.TextField(blank=True, verbose_name='排期说明')),
            ],
            options={
                'verbose_name': '排期明细',
                'verbose_name_plural': '排期明细',
                'ordering': ['start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_no', models.CharField(max_length=40, unique=True, verbose_name='订单编号')),
                ('project_name', models.CharField(max_length=160, verbose_name='项目名称')),
                ('test_requirements', models.TextField(verbose_name='试验需求')),
                ('status', models.CharField(choices=[('draft', '销售下单'), ('reviewing', '商务技术评审'), ('sales_revision', '销售修改/退单'), ('business_assign', '商务任务分配'), ('quality_scheduling', '质量部排期'), ('customer_confirm', '销售确认需求'), ('sample_register', '样品编号登记'), ('testing', '试验执行'), ('report_draft', '质量部出具报告'), ('sales_report_review', '销售审核报告'), ('gm_report_review', '总经理审核报告'), ('accounting_invoice', '会计开票'), ('closed', '办结'), ('cancelled', '退单')], default='draft', max_length=40, verbose_name='当前状态')),
                ('execution_mode', models.CharField(choices=[('suzhou', '苏州实验室'), ('jiangyin', '江阴实验室'), ('outsource', '外部委外'), ('mixed', '多路径并行')], default='mixed', max_length=20, verbose_name='执行路径')),
                ('expected_sample_arrival', models.DateField(blank=True, null=True, verbose_name='预计样品到达日期')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='预计交付日期')),
                ('quoted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='报价金额')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='加急订单')),
                ('chairman_visible', models.BooleanField(default=True, verbose_name='董事长可查看/审批')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='办结时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer', verbose_name='客户')),
                ('sales_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='销售负责人')),
            ],
            options={
                'verbose_name': 'LIMS订单',
                'verbose_name_plural': 'LIMS订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('invoice_no', models.CharField(max_length=80, unique=True, verbose_name='发票编号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='开票金额')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='开票日期')),
                ('note', models.TextField(blank=True, verbose_name='财务备注')),
                ('accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='会计')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.laborder', verbose_name='订单')),
            ],
            options={
                'verbose_name': '财务开票',
                'verbose_name_plural': '财务开票',
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stage', models.CharField(choices=[('before_sample', '样品到货前'), ('during_test', '试验进行中')], max_length=20, verbose_name='变更阶段')),
                ('reason', models.TextField(verbose_name='变更原因')),
                ('requested_changes', models.TextField(verbose_name='变更内容')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('accepted', '已接收'), ('applied', '已应用并回流排期'), ('rejected', '已驳回')], default='submitted', max_length=20, verbose_name='处理状态')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='core.laborder', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单更改单',
                'verbose_name_plural': '订单更改单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('business_passed', models.BooleanField(default=False, verbose_name='商务评审通过')),
                ('technical_passed', models.BooleanField(default=False, verbose_name='技术评审通过')),
                ('quotation_note', models.TextField(blank=True, verbose_name='报价说明')),
                ('feasibility_note', models.TextField(blank=True, verbose_name='可行性说明')),
                ('delivery_note', models.TextField(blank=True, verbose_name='交付周期说明')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='评审时间')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='评审人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.laborder', verbose_name='订单')),
            ],
            options={
                'verbose_name': '商务技术评审',
                'verbose_name_plural': '商务技术评审',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sample_no', models.CharField(max_length=60, unique=True, verbose_name='样品编号')),
                ('name', models.CharField(max_length=120, verbose_name='样品名称')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='收样时间')),
                ('storage_location', models.CharField(blank=True, max_length=120, verbose_name='存放位置')),
                ('note', models.TextField(blank=True, verbose_name='样品备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.laborder', verbose_name='订单')),
            ],
            options={
                'verbose_name': '样品台账',
                'verbose_name_plural': '样品台账',
                'ordering': ['sample_no'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=160, verbose_name='试验项目')),
                ('executor', models.CharField(blank=True, max_length=100, verbose_name='执行人/供应商')),
                ('status', models.CharField(choices=[('waiting', '待开始'), ('running', '试验中'), ('changing', '变更回流'), ('finished', '已完成')], default='waiting', max_length=20, verbose_name='试验状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('result_summary', models.TextField(blank=True, verbose_name='结果摘要')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='core.laborder', verbose_name='订单')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiments', to='core.sample', verbose_name='样品')),
                ('schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiments', to='core.scheduleitem', verbose_name='排期明细')),
            ],
            options={
                'verbose_name': '试验记录',
                'verbose_name_plural': '试验记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchedulePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='计划开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='计划完成日期')),
                ('summary', models.TextField(blank=True, verbose_name='项目总周期说明')),
                ('approved', models.BooleanField(default=False, verbose_name='周期表已确认')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_plan', to='core.laborder', verbose_name='订单')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='质量部负责人')),
            ],
            options={
                'verbose_name': '项目周期表',
                'verbose_name_plural': '项目周期表',
            },
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.scheduleplan', verbose_name='周期表'),
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('report_no', models.CharField(max_length=60, unique=True, verbose_name='报告编号')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('status', models.CharField(choices=[('draft', '质量部出具'), ('sales_review', '销售审核'), ('gm_review', '总经理审核'), ('approved', '审核通过'), ('rejected', '驳回重制')], default='draft', max_length=20, verbose_name='报告状态')),
                ('conclusion', models.TextField(blank=True, verbose_name='报告结论')),
                ('reject_reason', models.TextField(blank=True, verbose_name='驳回原因')),
                ('gm_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='总经理审核人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.laborder', verbose_name='订单')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_reports', to=settings.AUTH_USER_MODEL, verbose_name='编制人')),
                ('sales_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='销售审核人')),
            ],
            options={
                'verbose_name': '检测报告',
                'verbose_name_plural': '检测报告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('event_type', models.CharField(choices=[('status', '状态流转'), ('review', '审核'), ('change', '变更'), ('comment', '备注'), ('chairman', '董事长操作')], default='comment', max_length=20, verbose_name='事件类型')),
                ('from_status', models.CharField(blank=True, max_length=40, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, max_length=40, verbose_name='新状态')),
                ('note', models.TextField(blank=True, verbose_name='说明')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.laborder', verbose_name='订单')),
            ],
            options={
                'verbose_name': '流程日志',
                'verbose_name_plural': '流程日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
