# Generated by Django 6.0.6 on 2026-06-30 13:09

from django.db import migrations, models


def seed_test_standards(apps, schema_editor):
    TestStandard = apps.get_model('core', 'TestStandard')
    standards = [
        ('振动', 'GB/T 2423.10', '电工电子产品环境试验 第2部分：振动试验', '常用振动可靠性试验标准'),
        ('振动', 'IEC 60068-2-6', 'Environmental testing - Sinusoidal vibration', '正弦振动试验'),
        ('振动', 'IEC 60068-2-64', 'Environmental testing - Random vibration', '随机振动试验'),
        ('汽车', 'ISO 16750', '道路车辆 电气及电子设备环境条件和试验', '汽车电子环境可靠性'),
        ('汽车', 'GB/T 28046', '道路车辆 电气及电子设备环境条件和试验', '国内汽车电子环境试验'),
        ('汽车', 'LV 124', '汽车电子电气部件试验规范', '主机厂常用规范'),
        ('环境', 'GB/T 2423.1', '电工电子产品环境试验 第2部分：低温', '低温试验'),
        ('环境', 'GB/T 2423.2', '电工电子产品环境试验 第2部分：高温', '高温试验'),
        ('环境', 'GB/T 2423.3', '电工电子产品环境试验 第2部分：恒定湿热', '湿热试验'),
        ('材料', 'GB/T 10125', '人造气氛腐蚀试验 盐雾试验', '盐雾腐蚀'),
        ('材料', 'GB/T 16422', '塑料实验室光源暴露试验方法', '材料老化'),
    ]
    for industry, code, name, description in standards:
        TestStandard.objects.update_or_create(
            industry=industry,
            standard_code=code,
            defaults={
                'standard_name': name,
                'description': description,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('industry', models.CharField(max_length=64, verbose_name='行业分类')),
                ('standard_code', models.CharField(max_length=100, verbose_name='标准编号')),
                ('standard_name', models.CharField(max_length=200, verbose_name='标准名称')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '试验标准',
                'verbose_name_plural': '试验标准',
                'db_table': 'lims_test_standard',
                'ordering': ['industry', 'standard_code'],
                'unique_together': {('industry', 'standard_code')},
            },
        ),
        migrations.RunPython(seed_test_standards, migrations.RunPython.noop),
    ]
