# Generated by Django 6.0.6 on 2026-08-24 11:00

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_execution_attributes(apps, schema_editor):
    LabOrder = apps.get_model('core', 'LabOrder')
    LabOrder.objects.filter(execution_mode__in=[1, 2]).update(
        autonomous_execution=True,
        outsourced_execution=False,
    )
    LabOrder.objects.filter(execution_mode=3).update(
        autonomous_execution=False,
        outsourced_execution=True,
    )
    LabOrder.objects.filter(execution_mode=4).update(
        autonomous_execution=True,
        outsourced_execution=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teststandard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='autonomous_execution',
            field=models.BooleanField(default=True, verbose_name='包含自主试验'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='industry_category',
            field=models.CharField(choices=[('automotive', '汽车'), ('military', '军工'), ('other', '其他')], default='other', max_length=20, verbose_name='行业属性'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='outsourced_execution',
            field=models.BooleanField(default=False, verbose_name='包含委外试验'),
        ),
        migrations.RunPython(populate_execution_attributes, migrations.RunPython.noop),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', '合同'), ('attachment', '附件')], max_length=20, verbose_name='文件类型')),
                ('file', models.FileField(max_length=500, upload_to=core.models.order_document_upload_to, verbose_name='文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小（字节）')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.laborder', verbose_name='销售订单')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lims_uploaded_order_documents', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '订单合同与附件',
                'verbose_name_plural': '订单合同与附件',
                'db_table': 'lims_order_document',
                'ordering': ['document_type', 'create_time'],
            },
        ),
    ]
