# Generated by Django 6.0.6 on 2026-08-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_laborder_autonomous_execution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='test_method',
            field=models.TextField(blank=True, verbose_name='测试方法'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='test_standard',
            field=models.TextField(blank=True, verbose_name='测试标准'),
        ),
    ]
