# Generated by Django 6.0.6 on 2026-08-24 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_laborder_test_method_laborder_test_standard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='lead_lab_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lims_lead_orders', to=settings.AUTH_USER_MODEL, verbose_name='主责实验室负责人'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='sales_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='销售确认需求时间'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='workflow_version',
            field=models.PositiveSmallIntegerField(choices=[(1, 'V1 质量部调度流程'), (2, 'V2 技术直达实验室流程')], default=1, verbose_name='工作流版本'),
        ),
        migrations.AddField(
            model_name='scheduleplan',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lims_assigned_schedules', to=settings.AUTH_USER_MODEL, verbose_name='技术分配人'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='quality_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lims_registered_samples', to=settings.AUTH_USER_MODEL, verbose_name='样品登记人'),
        ),
        migrations.AlterField(
            model_name='scheduleplan',
            name='quality_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lims_quality_schedules', to=settings.AUTH_USER_MODEL, verbose_name='排期负责人'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='create_quality_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lims_created_reports', to=settings.AUTH_USER_MODEL, verbose_name='报告出具人'),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='workflow_version',
            field=models.PositiveSmallIntegerField(choices=[(1, 'V1 质量部调度流程'), (2, 'V2 技术直达实验室流程')], default=2, verbose_name='工作流版本'),
        ),
    ]
