# Generated by Django 6.0.6 on 2026-08-24 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_lab_devices(apps, schema_editor):
    LabDevice = apps.get_model('core', 'LabDevice')
    devices = [
        ('SZ-VIB-20T', '20吨振动台', 1, '20T', '振动、冲击、耐久试验'),
        ('SZ-VIB-50T', '50吨振动台', 1, '50T', '大型产品振动与冲击试验'),
        ('SZ-THV-001', '三综合试验箱', 1, '温湿振三综合', '温度、湿度、振动综合环境试验'),
        ('JY-VIB-20T', '20吨振动台', 2, '20T', '振动、冲击、耐久试验'),
        ('JY-VIB-50T', '50吨振动台', 2, '50T', '大型产品振动与冲击试验'),
        ('JY-THV-001', '三综合试验箱', 2, '温湿振三综合', '温度、湿度、振动综合环境试验'),
    ]
    for code, name, lab_type, model_spec, capability in devices:
        LabDevice.objects.get_or_create(
            device_code=code,
            defaults={
                'device_name': name,
                'lab_type': lab_type,
                'model_spec': model_spec,
                'capability': capability,
                'device_status': 1,
            },
        )


def remove_seed_lab_devices(apps, schema_editor):
    LabDevice = apps.get_model('core', 'LabDevice')
    LabDevice.objects.filter(device_code__in=[
        'SZ-VIB-20T', 'SZ-VIB-50T', 'SZ-THV-001',
        'JY-VIB-20T', 'JY-VIB-50T', 'JY-THV-001',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_laborder_lead_lab_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device_code', models.CharField(max_length=64, unique=True, verbose_name='设备编号')),
                ('device_name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('lab_type', models.PositiveSmallIntegerField(choices=[(1, '苏州实验室'), (2, '江阴实验室')], verbose_name='所属实验室')),
                ('model_spec', models.CharField(blank=True, max_length=200, verbose_name='规格型号')),
                ('capability', models.CharField(blank=True, max_length=500, verbose_name='试验能力')),
                ('device_status', models.PositiveSmallIntegerField(choices=[(1, '设备正常'), (2, '维修中'), (3, '设备停用')], default=1, verbose_name='设备状态')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='设备备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lims_created_devices', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '实验室设备',
                'verbose_name_plural': '实验室设备',
                'db_table': 'lims_lab_device',
                'ordering': ['lab_type', 'device_code'],
            },
        ),
        migrations.AddField(
            model_name='scheduleplan',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='core.labdevice', verbose_name='试验设备'),
        ),
        migrations.RunPython(seed_lab_devices, remove_seed_lab_devices),
    ]
