# Generated by Django 6.0.6 on 2026-08-25 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_lab_staff_profiles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    LabStaffProfile = apps.get_model('core', 'LabStaffProfile')
    Group.objects.get_or_create(name='实验操作员')
    for group_name, lab_type in [('苏州实验室', 1), ('江阴实验室', 2)]:
        group = Group.objects.filter(name=group_name).first()
        if not group:
            continue
        for user in group.user_set.all():
            LabStaffProfile.objects.update_or_create(
                user_id=user.id,
                defaults={'lab_type': lab_type, 'position': 'manager', 'is_active': True},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_labdevice_scheduleplan_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowevent',
            name='action_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='动作编码'),
        ),
        migrations.AddField(
            model_name='workflowevent',
            name='change_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='结构化变更内容'),
        ),
        migrations.AddField(
            model_name='workflowevent',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_events', to='core.scheduleplan', verbose_name='关联排期'),
        ),
        migrations.CreateModel(
            name='LabStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('lab_type', models.PositiveSmallIntegerField(choices=[(1, '苏州实验室'), (2, '江阴实验室')], verbose_name='所属实验室')),
                ('position', models.CharField(choices=[('manager', '实验室负责人'), ('operator', '实验操作员')], default='operator', max_length=20, verbose_name='实验室岗位')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在岗')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lims_lab_profile', to=settings.AUTH_USER_MODEL, verbose_name='员工账号')),
            ],
            options={
                'verbose_name': '实验室人员档案',
                'verbose_name_plural': '实验室人员档案',
                'db_table': 'lims_lab_staff_profile',
                'ordering': ['lab_type', 'position', 'user__username'],
            },
        ),
        migrations.RunPython(seed_lab_staff_profiles, migrations.RunPython.noop),
    ]
