# Generated by Django 6.0.6 on 2026-08-25 07:54

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_sample_arrivals(apps, schema_editor):
    SchedulePlan = apps.get_model('core', 'SchedulePlan')
    Sample = apps.get_model('core', 'Sample')
    for schedule in SchedulePlan.objects.all().iterator():
        sample = Sample.objects.filter(schedule_id=schedule.id).order_by('actual_arrive_time', 'id').first()
        if sample:
            SchedulePlan.objects.filter(pk=schedule.pk).update(
                sample_arrived=True,
                sample_arrived_at=sample.actual_arrive_time or sample.create_time,
                sample_confirmed_by_id=sample.quality_user_id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_workflowevent_action_code_workflowevent_change_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleplan',
            name='sample_arrived',
            field=models.BooleanField(default=False, verbose_name='样品是否已到'),
        ),
        migrations.AddField(
            model_name='scheduleplan',
            name='sample_arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='样品确认到达时间'),
        ),
        migrations.AddField(
            model_name='scheduleplan',
            name='sample_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lims_confirmed_sample_arrivals', to=settings.AUTH_USER_MODEL, verbose_name='到样确认人'),
        ),
        migrations.CreateModel(
            name='SamplePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=core.models.sample_photo_upload_to, verbose_name='样品照片')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小（字节）')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_photos', to='core.laborder', verbose_name='销售订单')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_photos', to='core.scheduleplan', verbose_name='项目排期')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lims_uploaded_sample_photos', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '样品到样照片',
                'verbose_name_plural': '样品到样照片',
                'db_table': 'lims_sample_photo',
                'ordering': ['create_time', 'id'],
            },
        ),
        migrations.RunPython(migrate_existing_sample_arrivals, migrations.RunPython.noop),
    ]
