# Generated by Django 6.0.6 on 2026-08-25 11:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_scheduleplan_sample_arrived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PDF 生成时间'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='report_file',
            field=models.FileField(blank=True, max_length=500, upload_to=core.models.report_pdf_upload_to, verbose_name='检测报告 PDF'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='report_type',
            field=models.CharField(choices=[('formal', '正式版'), ('draft', '草稿版'), ('data_only', '仅数据')], default='formal', max_length=20, verbose_name='报告版本'),
        ),
    ]
