# Generated by Django 6.0.6 on 2026-08-26 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_testreport_generated_at_testreport_report_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='outbound_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lims_outbound_samples', to=settings.AUTH_USER_MODEL, verbose_name='样品出库操作人'),
        ),
        migrations.AddField(
            model_name='sample',
            name='outbound_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='样品出库时间'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_status',
            field=models.PositiveSmallIntegerField(choices=[(1, '已登记待试验'), (2, '试验中'), (3, '试验完成'), (4, '已出库')], default=1, verbose_name='样品状态'),
        ),
    ]
