# Generated by Django 6.0.6 on 2026-08-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_experiment_test_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='order_status',
            field=models.PositiveSmallIntegerField(choices=[(1, '待评审'), (2, '评审驳回'), (3, '排期中'), (4, '试验中'), (5, '报告审核中'), (6, '已开票办结'), (7, '退单'), (8, '实验结果已提交待出报告'), (9, '实验已结束待提交结果')], default=1, verbose_name='订单状态'),
        ),
    ]
