# Generated by Django 6.0.6 on 2026-08-27 03:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_laborder_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_stage',
            field=models.CharField(choices=[('pre_review', '评审后预开票'), ('pre_experiment', '实验结束后预开票'), ('final', '最终总开票')], default='final', max_length=24, verbose_name='开票阶段'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_stage', 'final'), ('report__isnull', False)), fields=('report',), name='unique_final_invoice_per_report'),
        ),
    ]
