# Generated by Django 6.0.6 on 2026-08-27 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_invoice_invoice_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdocument',
            name='document_type',
            field=models.CharField(choices=[('contract', '合同'), ('outsource_contract', '委外合同'), ('attachment', '附件')], max_length=20, verbose_name='文件类型'),
        ),
        migrations.CreateModel(
            name='OutsourceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('outsource_company', models.CharField(max_length=200, verbose_name='委外公司')),
                ('outsource_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='委外金额')),
                ('entrust_order_no', models.CharField(db_index=True, max_length=64, verbose_name='委托单号')),
                ('undertaking_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='承接金额')),
                ('experiment_start_time', models.DateTimeField(verbose_name='委外实验开始时间')),
                ('experiment_end_time', models.DateTimeField(verbose_name='委外实验结束时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lims_created_outsource_requirements', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outsource_requirement', to='core.laborder', verbose_name='销售订单')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lims_updated_outsource_requirements', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '委外订单资料',
                'verbose_name_plural': '委外订单资料',
                'db_table': 'lims_outsource_requirement',
                'ordering': ['-create_time'],
            },
        ),
    ]
