# Generated by Django 6.0.6 on 2026-08-27 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_orderdocument_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_final_invoice_per_report',
        ),
        migrations.AddField(
            model_name='invoice',
            name='record_status',
            field=models.CharField(choices=[('valid', '有效'), ('voided', '已作废')], default='valid', max_length=16, verbose_name='发票状态'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='void_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='作废原因'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作废时间'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_lims_invoices', to=settings.AUTH_USER_MODEL, verbose_name='作废操作人'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_stage', 'final'), ('record_status', 'valid'), ('report__isnull', False)), fields=('report',), name='unique_final_invoice_per_report'),
        ),
    ]
