# Generated by Django 6.0.6 on 2026-09-23 05:15

from django.db import migrations, models


def replace_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='商务部')
    # Remove retired permissions, but preserve users and historical review attribution.
    Group.objects.filter(name__in=['商务', '技术', '商务评审', '技术评审']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_scheduleplan_scheduling_confirmation'),
    ]

    operations = [
        migrations.RunPython(replace_roles, migrations.RunPython.noop),
        migrations.AddField(
            model_name='laborder',
            name='review_reset_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='本轮评审起始时间'),
        ),
    ]
